In [1]:
import numpy as np

In [2]:
numpy_arr = np.array([1, 2, 3, 4])
print('Here is a NumPy array:', numpy_arr)
print('You know it is a NumPy array because its type is:', type(numpy_arr))

Here is a NumPy array: [1 2 3 4]
You know it is a NumPy array because its type is: <class 'numpy.ndarray'>


In [3]:
numpy_arr[2] = 200 #indexing the items of an array/list

In [4]:
numpy_arr # we treat it like a list?

array([  1,   2, 200,   4])

In [5]:
numpy_ndarr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(numpy_ndarr)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
list_of_integers = [0, 1, 2, 3]

In [12]:
list_of_integers = list_of_integers + [3]
list_of_integers

[0, 1, 2, 3, 3]

In [13]:
array_of_integers = np.array(list_of_integers)
# Add 3
array_of_integers + 3

array([3, 4, 5, 6, 6])

In [14]:
lengths_of_each_room = np.array([10, 12, 20, 5])
widths_of_each_room = np.array([13, 15, 16, 4])
areas_of_each_room = lengths_of_each_room * widths_of_each_room
print ('Here is an array with the square footages for each room:', areas_of_each_room)

Here is an array with the square footages for each room: [130 180 320  20]


In [15]:
type(areas_of_each_room)

numpy.ndarray

In [16]:
# Average temps in NYC from January -> December (in fahrenheit)
nyc_avg_temps_f = [39, 42, 50, 62, 72, 80, 85, 84, 76, 65, 54, 44]

# ----- Without NumPy -----
nyc_avg_temps_c = list(range(0,12))
nyc_avg_temps_c[0] = (nyc_avg_temps_f[0] - 32) * (5/9)
nyc_avg_temps_c[1] = (nyc_avg_temps_f[1] - 32) * (5/9)
nyc_avg_temps_c[2] = (nyc_avg_temps_f[2] - 32) * (5/9)
nyc_avg_temps_c[3] = (nyc_avg_temps_f[3] - 32) * (5/9)
nyc_avg_temps_c[4] = (nyc_avg_temps_f[4] - 32) * (5/9)
nyc_avg_temps_c[5] = (nyc_avg_temps_f[5] - 32) * (5/9)
nyc_avg_temps_c[6] = (nyc_avg_temps_f[6] - 32) * (5/9)
nyc_avg_temps_c[7] = (nyc_avg_temps_f[7] - 32) * (5/9)
nyc_avg_temps_c[8] = (nyc_avg_temps_f[8] - 32) * (5/9)
nyc_avg_temps_c[9] = (nyc_avg_temps_f[9] - 32) * (5/9)
nyc_avg_temps_c[10] = (nyc_avg_temps_f[10] - 32) * (5/9)
nyc_avg_temps_c[11] = (nyc_avg_temps_f[11] - 32) * (5/9)
# -------------------------

# ------ With NumPy -------
np_nyc_avg_temps_f = np.array(nyc_avg_temps_f)
np_nyc_avg_temps_c = (np_nyc_avg_temps_f - 32) * (5/9)
# -------------------------

print('1. Without NumPy:', nyc_avg_temps_c)
print('2. With NumPy:', np_nyc_avg_temps_c)

1. Without NumPy: [3.8888888888888893, 5.555555555555555, 10.0, 16.666666666666668, 22.22222222222222, 26.666666666666668, 29.444444444444446, 28.88888888888889, 24.444444444444446, 18.333333333333336, 12.222222222222223, 6.666666666666667]
2. With NumPy: [ 3.88888889  5.55555556 10.         16.66666667 22.22222222 26.66666667
 29.44444444 28.88888889 24.44444444 18.33333333 12.22222222  6.66666667]


In [20]:
# Control flow in functions

def func1(a):
    print(a + 1)
    print("Inside function func1")
    

In [21]:
def func2(b):
    print("Displaying the contents as is")
    print(b)
    func1(b) # -> goes and runs func1
    print("Inside function func2") # this occurs after func1

In [22]:
print("running the code here")
func2(10) # -> goes and runs func2
print("outside both functions")

running the code here
Displaying the contents as is
10
11
Inside function func1
Inside function func2
outside both functions


In [33]:
def addition(x,y) : # x and y are parameters, the type fo these parameters depend
    #on the values that are passed during the function call
    print("type of item a", type(x))
    print("type of item b", type(y))
    print(a+b)
    

In [34]:
a = 10
b = 20
addition(a,b) # a and b are arguments

type of item a <class 'int'>
type of item b <class 'int'>
30


In [36]:
import time

# Using 1 million integers
huge_list_of_integers = list(range(0, 1000000))
huge_np_array_of_integers = np.array(huge_list_of_integers)

def add_one(list_of_ints):
    return [num + 1 for num in list_of_ints]


start_time = time.perf_counter() # Time when operation starts
add_one(huge_list_of_integers) # Adds 1 to each number in the list of integers above
end_time = time.perf_counter() # Time when operation finishes
total_time = (end_time - start_time) # Total time for operation


start_time_with_np = time.perf_counter() # Time when operation starts
huge_np_array_of_integers + 1 # Adds 1 to each number in the array of integers
end_time_with_np = time.perf_counter() # Time when operation finishes
total_time_with_np = (end_time_with_np - start_time_with_np) # Total time for operation

print('Time it takes to add 1 to each element in a list without NumPy:', total_time)
print('Time it takes to add 1 to each element in a list with NumPy:', total_time_with_np)

percent_faster = int((((total_time - total_time_with_np)/total_time)*100))
print('NumPy completes the operation', percent_faster, '% faster than a traditional list')

Time it takes to add 1 to each element in a list without NumPy: 0.04272439999476774
Time it takes to add 1 to each element in a list with NumPy: 0.0009044999969773926
NumPy completes the operation 97 % faster than a traditional list


In [37]:
# An ordinary nested list
y = [[1, 2], [3, 4]]
print(type(y))
y

<class 'list'>


[[1, 2], [3, 4]]

In [38]:
# Reformatted as a NumPy array
y = np.array([[1, 2], [3, 4]])
print(type(y))
y

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [39]:
y.shape

(2, 2)

In [40]:
y = np.array([[1, 2, 3],[4, 5, 6]])
print(y.shape)
y

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
y = np.array([[1, 2],[3, 4],[5, 6]])
print(y.shape)
y

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
y = np.array([[[1, 2],[3, 4],[5, 6]],
             [[1, 2],[3, 4],[5, 6]]
             ])
print(y.shape)
y

(2, 3, 2)


array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [43]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [44]:
# Create a 1d array with 5 elements, all of which are 3
np.full(5, 3) 

array([3, 3, 3, 3, 3])

In [45]:
# Create a 1d array with 5 elements, filling them with the values 0 to 4
np.full(5, range(5)) 

array([0, 1, 2, 3, 4])

In [46]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x.shape)
x

(4, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
# Retrieving all rows after the first row
x[1:] 

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
# Retrieving all rows after the first row
x[1:] 

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
# Rows 2 through 4, columns 1 through 3
x[2:4,1:3] 

array([[ 8,  9],
       [11, 12]])